"""L2 project summary tools for the resume-resume MCP server.

Exposes pre-computed hierarchical project summaries from insights.db.
These summaries are generated by the daemon via claude-session-commons
hierarchy module and stored in the summary_levels table.
"""

import json
from pathlib import Path

from .progress import progress


def register_l2_tools(mcp_instance):
    """Register L2/L3 summary tools on the MCP server."""

    def _get_conn():
        from claude_session_commons.insights import get_db
        return get_db()

    @mcp_instance.tool()
    def project_summary(project_path: str) -> dict | str:
        """Get the L2 topic summaries for a project.

        Returns pre-computed workstream summaries: status, narrative,
        key decisions, and open threads. Instant (<200ms) when available.
        Use this instead of searching individual sessions for project context.
        """
        conn = _get_conn()

        # L2 summaries are stored per-topic with entity_id = "path::topic"
        rows = conn.execute(
            """SELECT entity_id, title, summary_text, source_ids,
                      updated_at
               FROM summary_levels
               WHERE level = 2 AND entity_id LIKE ? || '::%'
               ORDER BY updated_at DESC""",
            (project_path,),
        ).fetchall()

        if not rows:
            return f"No L2 summaries for {project_path}. Run daemon to generate."

        topics = []
        for r in rows:
            try:
                summary = json.loads(r[2]) if isinstance(r[2], str) else r[2]
            except (json.JSONDecodeError, TypeError):
                summary = {"raw": r[2]}

            source_ids = []
            if r[3]:
                try:
                    source_ids = json.loads(r[3]) if isinstance(r[3], str) else r[3]
                except (json.JSONDecodeError, TypeError):
                    pass

            topics.append({
                "topic": summary.get("topic_name", r[1]),
                "status": summary.get("status", ""),
                "narrative": summary.get("narrative", ""),
                "key_decisions": summary.get("key_decisions", []),
                "open_threads": summary.get("open_threads", []),
                "session_count": len(source_ids),
                "updated_at": r[4],
            })

        project_name = Path(project_path).name
        return {
            "project": project_name,
            "project_path": project_path,
            "topic_count": len(topics),
            "topics": topics,
        }

    @mcp_instance.tool()
    def list_projects(limit: int = 30) -> list[dict]:
        """List all known projects with session counts and last activity.

        Returns projects ordered by most recent activity. Use to find
        which projects have L2 summaries available.
        """
        conn = _get_conn()

        from claude_session_commons.insights import list_projects as _list_projects
        projects = _list_projects(conn, limit=limit)

        # Annotate with L2 availability
        l2_projects = set()
        l2_rows = conn.execute(
            "SELECT DISTINCT entity_id FROM summary_levels WHERE level = 2"
        ).fetchall()
        for r in l2_rows:
            # entity_id format: /path/to/project::Topic Name
            path = r[0].split("::")[0] if "::" in r[0] else r[0]
            l2_projects.add(path)

        result = []
        for p in projects:
            result.append({
                "name": p["name"],
                "path": p["path"],
                "session_count": p["session_count"],
                "last_activity": p["last_activity"],
                "has_l2": p["path"] in l2_projects,
            })
        return result

    @mcp_instance.tool()
    def project_orient(project_path: str) -> dict:
        """Single-call project orientation — everything you need to resume work.

        Returns in one call: L2 topic summaries, git dirty state, most recent
        bookmark, and session count. Designed for /takeoff to call once instead
        of making 3-5 separate tool calls.
        """
        import subprocess

        project_name = Path(project_path).name
        p_ctx = progress(f"orient: {project_name}")
        p = p_ctx.__enter__()

        result = {
            "project": project_name,
            "project_path": project_path,
        }

        # 1. L2 summaries (instant from DB)
        p.update(f"Loading L2 summaries for {project_name}...", icon="search")
        conn = _get_conn()
        rows = conn.execute(
            """SELECT title, summary_text, updated_at
               FROM summary_levels
               WHERE level = 2 AND entity_id LIKE ? || '::%'
               ORDER BY updated_at DESC""",
            (project_path,),
        ).fetchall()

        if rows:
            topics = []
            for r in rows:
                try:
                    s = json.loads(r[1]) if isinstance(r[1], str) else r[1]
                except (json.JSONDecodeError, TypeError):
                    s = {}
                topics.append({
                    "topic": s.get("topic_name", r[0]),
                    "status": s.get("status", ""),
                    "open_threads": s.get("open_threads", []),
                })
            result["topics"] = topics
            result["l2_updated"] = rows[0][2]
            p.update(f"Found {len(topics)} topics", icon="done")
            for t in topics[:4]:
                p.result(t["topic"], t["status"][:80])
        else:
            result["topics"] = None
            result["l2_updated"] = None
            p.update("No L2 summaries yet", icon="info")

        # 2. Git dirty state (fast subprocess)
        p.update("Checking git state...", icon="working")
        if Path(project_path).is_dir():
            try:
                git_status = subprocess.run(
                    ["git", "status", "--porcelain"],
                    cwd=project_path, capture_output=True, text=True, timeout=5,
                )
                lines = [l for l in git_status.stdout.strip().split("\n") if l]
                result["git_dirty"] = len(lines) > 0
                result["git_dirty_count"] = len(lines)
                git_branch = subprocess.run(
                    ["git", "branch", "--show-current"],
                    cwd=project_path, capture_output=True, text=True, timeout=5,
                )
                result["git_branch"] = git_branch.stdout.strip()
                dirty_msg = f"{len(lines)} dirty files" if lines else "clean"
                p.update(f"{result['git_branch']}, {dirty_msg}", icon="done")
            except (subprocess.TimeoutExpired, FileNotFoundError):
                result["git_dirty"] = None
                result["git_branch"] = None
        else:
            result["git_dirty"] = None
            result["git_branch"] = None

        # 3. Most recent bookmark for this project
        p.update("Reading latest bookmark...", icon="working")
        bookmarks_dir = Path.home() / ".claude" / "bookmarks"
        latest_bookmark = None
        latest_ts = 0
        if bookmarks_dir.is_dir():
            for bf in bookmarks_dir.glob("*-bookmark.json"):
                try:
                    data = json.loads(bf.read_text())
                    bp = data.get("project", {}).get("path", "")
                    if bp == project_path and bf.stat().st_mtime > latest_ts:
                        latest_ts = bf.stat().st_mtime
                        latest_bookmark = {
                            "state": data.get("lifecycle_state", "unknown"),
                            "summary": data.get("context", {}).get("summary", ""),
                            "next_actions": data.get("context", {}).get("next_actions", []),
                            "blockers": data.get("context", {}).get("blockers", []),
                            "confidence": data.get("context", {}).get("confidence", ""),
                        }
                except (json.JSONDecodeError, OSError):
                    continue
        result["bookmark"] = latest_bookmark
        if latest_bookmark:
            p.update(f"Bookmark: {latest_bookmark['state']}", icon="done")
        else:
            p.update("No bookmark found", icon="info")

        # 4. Session count from projects table
        try:
            row = conn.execute(
                "SELECT session_count, last_activity FROM projects WHERE path = ?",
                (project_path,),
            ).fetchone()
            if row:
                result["session_count"] = row[0]
                result["last_activity"] = row[1]
        except Exception:
            pass

        p.update("Ready", icon="done", highlight=True)
        p_ctx.__exit__(None, None, None)

        return result
